### ISSUE TITLE
Upgrade to thumbor 7

### ISSUE THREAD

**Issue by heynemann** [arcivr/thumbor-padding#1]
Hey this seems like a very useful filter! Do you think we can work together to upgrade it to thumbor 7?

Anyways, great job! Adding this to awesome thumbor list of projects.

**Comment by dereklucas** [comment]
@heynemann Thanks! You're welcome to do whatever you'd like with this, and it should be simple to update since it's a pretty straightforward script. Unfortunately, however, we're not actively using it and don't currently have the bandwidth to maintain it.

Good luck!
